### ISSUE TITLE
ErrBitStateNotFound error is missing

### ISSUE THREAD

**Issue by yaronius** [rinchsan/device-check-go#11]
Hi! I come from an older version of this library which was `github.com/snowman-mh/device-check-go` and it is redirecting me to this repo now. And I see that the older version was using `ErrBitStateNotFound` which is missing in this repository. The only trace of this error is found in README and is kind of misleading because the SDK doesn't return this error now:
```go
if err := client.QueryTwoBits("DEVICE_TOKEN_FROM_CLIENT", &result); err != nil {
	// error handling
	// Note that SDK returns ErrBitStateNotFound error if no bits found
}
```
What would be a suitable replacement for this error in the current version of SDK? I browsed the code and didn't find any. It would be nice to update the README as well.

**Comment by rinchsan** [comment]
@yaronius 
Thank you for filing a bug!

This issue was fixed by #12 (thanks to @peter-meemo) and some more tests were added by #13 .
And I released a new version https://github.com/rinchsan/device-check-go/releases/tag/v1.2.0 including above bug fixes.

Feel free to re-open this or open a new one if you find any degradations.
