### ISSUE TITLE
returned errors discard information in response body

### ISSUE THREAD

**Issue by peter-meemo** [rinchsan/device-check-go#21]
Apple's devicecheck endpoints return errors with both an error code and a response body. Multiple response bodies can be produced for the same error code [(see here)](https://developerinsider.co/devicecheck-api-unique-identifier-for-the-ios-devices/)*. e.g., 401 can represent an expired token or an invalid token. 

The library currently maps each response code to a separate error object (e.g. 401 is mapped to `ErrUnauthorized`). This means that we cannot tell what the details of the error are. For some errors like 400 that can have many different reasons, this makes debugging challenging.

Proposed solution: instead of mapping response codes to static errors with static strings, create errors by mapping the response codes to an instance of an error type on a per-code basis, with that instance containing the response body string. This allows calling code to continue checking the error type, but preserves the details of the error. [Basically, use go 1.13 style errors](https://blog.golang.org/go1.13-errors).

* Apple used to have these response codes in their documentation, but I can't find them now that they've rewritten it for AppAttest...

**Comment by rinchsan** [comment]
@peter-meemo 
Thank you for filing an issue!
And your proposal looks good!

I think it's good to make `newError` wrap an existing`devicecheck.ErrXxx` with adding response body text by using `fmt.Errorf`, so that we can use Go 1.13 style errors as you mentioned.
I'm gonna start working on this!

Btw, you can see DeviceCheck API response list on this official docs:
https://developer.apple.com/documentation/devicecheck/accessing_and_modifying_per-device_data
We've added this document on this repo's README.

**Comment by peter-meemo** [comment]
Thank you!
